version: "3.7"

services:
  psql:
    container_name: cat_psql
    image: postgres
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ./data/:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: cat_redis
    hostname: redis_boot
    restart: always
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
